spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: "21Q2VD9txfpkGj8TyYof"
            client-secret: "o1Fjw_DuHK"
            redirect-url: "http://localhost:8888/member/callback" == "http://localhost:8888/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: name, email
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response